version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    ports:
      - '3306:3306'
    volumes:
      - db_storage:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}',
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_storage:/data

  # api:
  #   build:
  #     context: .
  #     dockerfile: DevDockerfile
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #     - '9229:9229'
  #   volumes:
  #     - ./:/api
  #     - /api/node_modules
  #   depends_on:
  #     - db

volumes:
  db_storage:
  redis_storage:
